### PR TITLE
Fix travis chrome

### PR DESCRIPTION
**Pull request by keller-mark**
Travis did not like the chrome configuration https://travis-ci.org/github/hms-dbmi/vitessce-grid/builds/685838768#L419

### CODE REVIEW

**Comment by ilan-gold** [comment]
What's going on with the `package-lock.json`?

**Comment by ilan-gold** [comment]
Oh I see.  dependabot...

**Comment by keller-mark** [comment]
If by previously you are asking about the behavior with NWB, it looks like they use "Chrome" when it detects the `karma-chrome-launcher` plugin https://github.com/insin/nwb/blob/master/src/createKarmaConfig.js#L107

If by previously you are asking about the behavior before the last pull request was merged, and why the commits had a green check in the PR, but then failed after merging, I was wondering that too. I just checked and it looks like it had a green check for something that was not actually travis... I had not realized that. I assumed that the green check meant travis passed.

Screen Shot 2020-05-11 at 6 27 55 PM

**Comment by ilan-gold** [comment]
That was what I was wondering.  Sounds good.

**Pull request merged**
